package:
  name: anaconda-project
  version: {{ environ.get('GIT_DESCRIBE_TAG', '').replace('v', '') }}

source:
  git_url: ../
  git_tag: {% if environ.get('PRERELEASE', '') %} HEAD {% else %} {{ environ.get('GIT_DESCRIBE_TAG') }} {% endif %}
  # If you're trying to test build changes, you have to add this
  # pointing to the branch you're modifying.
  # git_tag: package-script

build:
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}
  script: python setup.py install --single-version-externally-managed --record=record.txt
  entry_points:
    - anaconda-project = anaconda_project.cli:main

requirements:
  build:
    - python
    - setuptools

  run:
    - anaconda-client
    - python
    - requests
    - ruamel_yaml
    - tornado

test:
  imports:
    - anaconda_project

  commands:
    - echo "First of test commands"
    - anaconda-project --help
    - anaconda-project --version
    - echo "Last of test commands"

about:
  home: https://github.com/Anaconda-Platform/anaconda-project
  license: BSD 3-Clause
  license_family: BSD
  summary: Reproducible, executable project directories.
  description: |
    By adding an anaconda-project.yml to a project directory, a single 
    anaconda-project runcommand will be able to set up all dependencies 
    and then launch the project.
  doc_url: http://anaconda-project.readthedocs.io
  dev_url: https://github.com/Anaconda-Platform/anaconda-project
