name: Build and test
on:
  push:
    branches:
      - master
    tags:
      - '*'
  pull_request:
    branches:
      - master
jobs:
  package:
    runs-on: ubuntu-latest
    steps:
    - name: Retrieve the source code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - uses: conda-incubator/setup-miniconda@v3
      with:
        auto-update-conda: true
        python-version: "3.12"
        auto-activate-base: true
        activate-environment: ""
    - name: Install build dependencies
      shell: bash -el {0}
      run: |
        conda config --append channels conda-forge
        conda install -y conda-build conda-verify flake8 pydocstyle sphinx pydata-sphinx-theme==0.14.4 sphinx-copybutton sphinx-notfound-page
    - name: Verify formatting compliance
      shell: bash -el {0}
      run: |
        flake8 anaconda_project
        pydocstyle anaconda_project
    - name: Build the documentation as a test
      shell: bash -el {0}
      run: |
        cd docs
        make html
    - name: Build the package
      shell: bash -el {0}
      run: conda build --no-test conda.recipe
    - name: Reduce the size of the build artifact
      shell: bash -el {0}
      run: rm -rf ${CONDA}/conda-bld/{git_cache,work,anaconda-project*,*/.cache}
    - name: Upload the build artifact
      uses: actions/upload-artifact@v4
      with:
        name: package-${{ github.sha }}
        path: ${{ env.CONDA }}/conda-bld

  tests:
    defaults:
      run:
        shell: bash
    runs-on: ${{ matrix.os }}
    needs: package
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        pyver: ["3.10", "3.11", "3.12", "3.13", "3.14"]
        exclude:
          # Python 3.14 is still in development
          - os: windows-latest
            pyver: "3.14"
          - os: macos-latest
            pyver: "3.14"
    steps:
    - name: Retrieve the source code
      uses: actions/checkout@v4
    - uses: conda-incubator/setup-miniconda@v3
      with:
        auto-update-conda: true
        python-version: ${{ matrix.pyver }}
        auto-activate-base: true
    - name: Download the build artifact
      uses: actions/download-artifact@v4
      with:
        name: package-${{ github.sha }}
        path: ./conda-bld
    - name: Configure conda channels
      shell: bash -el {0}
      run: |
        conda config --prepend channels conda-forge
        conda config --append channels ./conda-bld
        conda index ./conda-bld
    - name: Build the test environment
      shell: bash -el {0}
      run: |
        conda create -y -n anaconda-project-dev python=${{ matrix.pyver }} \
          coverage pytest pytest-cov redis notebook bokeh \
          keyring setuptools pip anaconda-project
    - name: Run the tests
      shell: bash -el {0}
      run: |
        conda activate anaconda-project-dev
        pytest -vrfe --durations=10 \
          --cov-config=.coveragerc --cov-report=term-missing \
          --cov-fail-under=95 --cov-report=xml:./coverage.xml \
          --cov=anaconda_project anaconda_project
    - name: Upload coverage
      uses: codecov/codecov-action@v4
      if: matrix.os == 'ubuntu-latest' && matrix.pyver == '3.12'
      with:
        file: ./coverage.xml
        fail_ci_if_error: false
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  upload:
    needs: tests
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:
    - name: Retrieve the source code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - uses: conda-incubator/setup-miniconda@v3
      with:
        auto-update-conda: true
        python-version: "3.12"
        auto-activate-base: true
    - name: Download the build artifacts
      uses: actions/download-artifact@v4
      with:
        name: package-${{ github.sha }}
        path: conda-bld
    - name: Upload to anaconda.org
      shell: bash -el {0}
      env:
        ANACONDA_TOKEN: ${{ secrets.ANACONDA_TOKEN }}
        GITHUB_REF: ${{ github.ref }}
      run: |
        conda install -y anaconda-client
        [[ "$GITHUB_REF" =~ ^refs/tags/ ]] || export LABEL="--label dev"
        anaconda --verbose --token $ANACONDA_TOKEN upload --user ctools $LABEL conda-bld/*/*.tar.bz2 --force
